<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [gpodder-devel] [patch] Add a message to AttributeError in config.py
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/gpodder-devel/2009-January/index.html" >
   <LINK REL="made" HREF="mailto:gpodder-devel%40lists.berlios.de?Subject=Re%3A%20%5Bgpodder-devel%5D%20%5Bpatch%5D%20Add%20a%20message%20to%20AttributeError%20in%20config.py&In-Reply-To=%3C1231013287.5281.16.camel%40lightweight%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="001989.html">
   <LINK REL="Next"  HREF="001976.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[gpodder-devel] [patch] Add a message to AttributeError in config.py</H1>
    <B>Ville-Pekka Vainio</B> 
    <A HREF="mailto:gpodder-devel%40lists.berlios.de?Subject=Re%3A%20%5Bgpodder-devel%5D%20%5Bpatch%5D%20Add%20a%20message%20to%20AttributeError%20in%20config.py&In-Reply-To=%3C1231013287.5281.16.camel%40lightweight%3E"
       TITLE="[gpodder-devel] [patch] Add a message to AttributeError in config.py">vpivaini at cs.helsinki.fi
       </A><BR>
    <I>Sat Jan  3 21:08:07 CET 2009</I>
    <P><UL>
        <LI>Previous message: <A HREF="001989.html">[gpodder-devel] Status of translations in gPodder
</A></li>
        <LI>Next message: <A HREF="001976.html">[gpodder-devel] [patch]&#160;Add option to clear the genre tag when updating tags
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1975">[ date ]</a>
              <a href="thread.html#1975">[ thread ]</a>
              <a href="subject.html#1975">[ subject ]</a>
              <a href="author.html#1975">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi,

I was hacking around the media file tagging code a bit (maybe more about
that later when I actually have some working code to show) and I noticed
that if you try to use a config variable which doesn't exist,
config.py's __getattr__ just raises an AttributeError without a message.

If you happen to try to use a non-existing config variable inside a
try-catch where you catch Exception and then log its message, the
resulting error message isn't going to be very helpful when the caught
Exception itself has no message.

The attached patch adds a simple message to the AttributeError which is
raised by config.py if a non-existing config variable is attempted to be
used.


-- 
Ville-Pekka Vainio
-------------- next part --------------
A non-text attachment was scrubbed...
Name: gpodder_config_raise_description.patch
Type: text/x-patch
Size: 442 bytes
Desc: not available
URL: &lt;<A HREF="https://lists.berlios.de/pipermail/gpodder-devel/attachments/20090103/09bc8288/attachment.bin">https://lists.berlios.de/pipermail/gpodder-devel/attachments/20090103/09bc8288/attachment.bin</A>&gt;
</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="001989.html">[gpodder-devel] Status of translations in gPodder
</A></li>
	<LI>Next message: <A HREF="001976.html">[gpodder-devel] [patch]&#160;Add option to clear the genre tag when updating tags
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1975">[ date ]</a>
              <a href="thread.html#1975">[ thread ]</a>
              <a href="subject.html#1975">[ subject ]</a>
              <a href="author.html#1975">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/gpodder-devel">More information about the gpodder-devel
mailing list</a><br>
</body></html>
